// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210601140949_ThirdCreate")]
    partial class ThirdCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Domain.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CityName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ZipCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("CityId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Domain.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Domain.Doctor", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("d_city")
                        .HasColumnType("TEXT");

                    b.Property<string>("d_country")
                        .HasColumnType("TEXT");

                    b.Property<string>("d_fname")
                        .HasColumnType("TEXT");

                    b.Property<char>("d_gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("d_lname")
                        .HasColumnType("TEXT");

                    b.Property<string>("d_phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("d_postal_code")
                        .HasColumnType("TEXT");

                    b.Property<string>("d_street_address")
                        .HasColumnType("TEXT");

                    b.Property<string>("designation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dob")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("DoctorInfo");
                });

            modelBuilder.Entity("Domain.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dob")
                        .HasColumnType("TEXT");

                    b.Property<string>("other_det")
                        .HasColumnType("TEXT");

                    b.Property<string>("p_city")
                        .HasColumnType("TEXT");

                    b.Property<string>("p_country")
                        .HasColumnType("TEXT");

                    b.Property<string>("p_fname")
                        .HasColumnType("TEXT");

                    b.Property<char>("p_gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("p_lname")
                        .HasColumnType("TEXT");

                    b.Property<string>("p_phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("p_postal_code")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("p_rdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("p_street_address")
                        .HasColumnType("TEXT");

                    b.Property<int>("p_weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PatientInfo");
                });

            modelBuilder.Entity("Domain.Receptionist", b =>
                {
                    b.Property<Guid>("ReceptionistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("city")
                        .HasColumnType("TEXT");

                    b.Property<string>("country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dob")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<char>("gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<int>("phone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("postal_code")
                        .HasColumnType("TEXT");

                    b.Property<string>("street_address")
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.HasKey("ReceptionistId");

                    b.ToTable("Receptionists");
                });

            modelBuilder.Entity("Domain.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("floor_no")
                        .HasColumnType("INTEGER");

                    b.Property<string>("r_type")
                        .HasColumnType("TEXT");

                    b.Property<string>("stauts")
                        .HasColumnType("TEXT");

                    b.Property<int>("tot_bed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("tot_bed_occupied")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RoomInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
